@startuml
title Diagramme de déploiement PATO
skinparam shadowing false
skinparam monochrome reverse
scale 1280*900
node E_Robot
node E_Phone
E_Robot -r- E_Phone : Wifi
[Soft C] ..> [E_Lib MrPIZ] : <<deploy>>
[Soft C] ..> E_Robot : <<deploy>>
[E_Lib MrPIZ] ..> E_Robot : <<deploy>>
[App Android] ..> E_Phone : <<deploy>>
@enduml