@startuml
title 2.2.1 - Architecture matérielle et logicielle
skinparam shadowing false
skinparam monochrome reverse
scale 1280*900
node Robot
node Phone
Robot -r- Phone : Wifi
[Soft C] ..> [E_Lib MrPIZ] : <<deploy>>
[Soft C] ..> Robot : <<deploy>>
[E_Lib MrPIZ] ..> Robot : <<deploy>>
[App Android] ..> Phone : <<deploy>>
@enduml
