@startuml
title 2.2.1 - Architecture matérielle et logicielle
scale 1280*900
node Robot
node Phone
Robot -r- Phone : Wifi
[MARCO C] ..> [E_Lib MrPIZ] : <<deploy>>
[MARCO C] ..> Robot : <<deploy>>
[E_Lib MrPIZ] ..> Robot : <<deploy>>
[MARCO Android] ..> Phone : <<deploy>>
@enduml
