@startuml
[*] --> Ecran
state Ecran {
    state "NonConnecté" as NonConnecté
    state "EP" as EP
    state "Verrouillé" as Verrouillé
    state "SelectionExplo" as SelectionExplo

    state c <<choice>>

    [*] --> NonConnecté
    NonConnecté --> c : SeConnecter()

    c --> NonConnecté : [Connection Perdue]
    c --> EP
    c --> Verrouillé : [robotVerrouillé]
    EP --> SelectionExplo : AppuieLancerExplo()
    SelectionExplo --> EP : LancerExplo()
}

Ecran --> [*] : quitter()

@enduml