@startuml
state "LED_Eteinte" as LED_Eteinte
state "LED_Rouge" as LED_Rouge
state "LED_Verte" as LED_Verte
state "LED_Bleu" as LED_Bleu
state c <<choice>>

[*] --> LED_Eteinte
LED_Eteinte --> c : control_led()
c --> LED_Rouge : control_led_rouge()
c --> LED_Verte : control_led_verte()
c --> LED_Bleu : control_led_bleu()

@enduml
