@startuml

[*] --> Ecran
note on link
    Fait par demarrer()
end note
state Ecran {
    state "EcranNonConnecté" as EcranNonConnecté
    state "EP" as EP
    state "EcranVerrouillé" as EcranVerrouillé
    state "SelectionExplo" as SelectionExplo

    state c <<choice>>

    [*] --> EcranNonConnecté
    EcranNonConnecté --> c : SeConnecter()

    c --> EcranNonConnecté : [Connection Perdue]
    c --> EP
    c --> EcranVerrouillé : [robotVerrouille]
    EcranVerrouillé --> EP: Verrouillage()
    EP --> EcranVerrouillé :Deverrouillage()
    EP --> SelectionExplo : SelectAlgo()
    SelectionExplo --> EP : Valide()
    SelectionExplo --> EP : Annule()
}

Ecran --> [*] : quitter()

@enduml