@startuml
[*] --> Screen
note on link
    Done by start()
end note
state Screen {
    state "NotConnectedScreen" as NotConnectedScreen
    state "MainScreen" as MainScreen
    state "LockedScreen" as LockedScreen
    state "ExploSelection" as ExploSelection

    state c <<choice>>

    [*] --> NotConnectedScreen
    NotConnectedScreen -> c : Connection()

    c --> NotConnectedScreen : [Connection Lost]
    c --> MainScreen
    c --> LockedScreen : [robotLocked]
    LockedScreen --> MainScreen: Unlock()
    MainScreen --> LockedScreen: Lock()
    MainScreen --> ExploSelection : SelecAlgo()
    ExploSelection --> MainScreen : Confirm()
    ExploSelection --> MainScreen : Cancel()
}

Screen --> [*] : Quit()

@enduml