@startuml
[*] --> Screen
state Screen {
    state "NotConnected" as NotConnected
    state "MainScreen" as MainScreen
    state "Locked" as Locked
    state "ExploSelection" as ExploSelection

    state c <<choice>>

    [*] --> NotConnected
    NotConnected -> c : Connection()

    c --> NotConnected : [Connection Lost]
    c --> MainScreen
    c --> Locked : [robotLocked]
    MainScreen --> ExploSelection : LaunchExplo()
    ExploSelection --> MainScreen : LaunchExplo()
}

Screen --> [*] : Quit()

@enduml