@startuml
[*] --> Ecran
note on link
    Fait par demarrer()
end note
state Ecran {
    state "EcranNonConnecté" as EcranNonConnecté
    state "EcranPrincipal" as EcranPrincipal
    state "EcranVerrouillé" as EcranVerrouillé
    state "EcranSelectionExplo " as EcranSelectionExplo 
     state "EcranOption" as EcranOption

    state c <<choice>>

    [*] --> EcranNonConnecté
    EcranNonConnecté --> c : SeConnecter()

    c --> EcranNonConnecté : [Connection Perdue]
    c --> EcranPrincipal
    c --> EcranVerrouillé : [robotVerrouille]
    EcranVerrouillé --> EcranPrincipal: Verrouillage()
    EcranPrincipal--> EcranVerrouillé :Deverrouillage()
    EcranPrincipal--> EcranSelectionExplo : SelectAlgo()
    EcranSelectionExplo --> EcranPrincipal: Valide()
    EcranSelectionExplo --> EcranPrincipal: Annule()
    EcranPrincipal--> EcranOption :SelectOption()
    EcranOption --> EcranPrincipal:Valide()
    EcranOption --> EcranPrincipal:Annule()
}

Ecran --> [*] : quitter()
@enduml
