@startuml
'https://plantuml.com/use-case-diagram

title CU Stratégique : Évaluer les algorithmes d’exploration cartographique
skinparam shadowing false



Utilisateur as Utilisateur 
Robot as Robot

Utilisateur -right- (Évaluer les algorithmes d’exploration cartographique)
Robot -left- (Évaluer les algorithmes d’exploration cartographique)
(Évaluer les algorithmes d’exploration cartographique) -.> (Initialiser le système MARCO) : include
(Évaluer les algorithmes d’exploration cartographique) -.> (Lancer une exploration) : include
(Évaluer les algorithmes d’exploration cartographique) -.> (Éteindre MARCO) : include
@enduml
