@startuml
title 2.2.2 - Interfaces du systèmes
scale 1024*768
actor Utilisateur as U
actor ROBOT as P

rectangle "<u>SàE</u>" as S{
}
rectangle "<u>E_Lib_MrPIZ</u>" as L{
}


U -right- S : demarrer() <&arrow-right>\n set_explo_algorithm(algo) <&arrow-right>\n lancer_explo() <&arrow-right>\n control_manuel() <&arrow-right>\n quitter() <&arrow-right>\n \n<&arrow-left> afficher_niveau_batterie() \n <&arrow-left> afficher_map() \n
S-right-L : init() <&arrow-right> \n fermer()<&arrow-right> \n control_led()<&arrow-right> \n get_sensors(): position<&arrow-right> \n init_position()<&arrow-right> \n reset_sensors()<&arrow-right> \n recup_niveau_batterie(): niveau_batterie<&arrow-right> \n
L-right-P : deplacer(mvt) <&arrow-right> \n detect_obstacle() <&arrow-right> \n recup_position_robot() <&arrow-right> \n
@enduml